### PR TITLE
enable building on qemu

### PR DESCRIPTION
**Pull request by norbusan**
This pull requests enables building on qemu, and adds a script that does the actual build.

### CODE REVIEW

**Review by hongquan — CHANGES_REQUESTED** [review]
Please provide a log to prove that the build process is clean, no error, no warning.

**Comment by norbusan** [comment]
This is the build output capturing stdout and stderr
[build.log.txt](https://github.com/fossasia/pi-gen/files/3006381/build.log.txt)

Here is the log generated by the `pi-gen/build.sh` script itself in `../Work/build.log`
[build.log](https://github.com/fossasia/pi-gen/files/3006384/build.log)

**Review by hongquan — APPROVED** [review]

**Comment by norbusan** [comment]
I sent a PR to the ReSpeaker github project, see https://github.com/respeaker/seeed-voicecard/pull/147
Let us hope they merge or adopt something similar.

**Comment by hongquan** [comment]
While we are waiting for ReSpeaker's response, could you please move the code which patches ReSpeaker's install script to SUSI Linux's _install.sh_ (create a PR)?

**Comment by norbusan** [comment]
Done so: https://github.com/fossasia/susi_linux/pull/471

**Review by mariobehling — APPROVED** [review]

**Comment by hongquan** [comment]
@norbusan Do you have any explanation for this code:

```sh
export LANG=C
```

C locale is very limited. I don't want it to be baked into final image.

**Comment by norbusan** [comment]
It is not the one that is baked into the final image, but the one the build script is running under. I had `en_US.UTF-8` set in my environment, but this locale is initially not supported in the qemu build process, and this lots of warning messages that en_US.UTF-8 is not supported and the locale is being reset to C.

In the baked image the default setting as decided by the raspian installation is the default.

**Comment by Orbiter** [comment]
wow! 👍

**Pull request merged**
